### ISSUE TITLE
`prettify.format` is possibly undefined

### ISSUE THREAD

**Issue by bmaupin** [panoply/prettify#1]
I'm using this code with prettify 0.5.5-beta.1:

```typescript
import prettify from '@liquify/prettify';

await prettify.format(sourceXml, { language: 'xml' });
```

I'm getting a TypeScript error on `prettify.format`:

> Cannot invoke an object which is possibly 'undefined'.ts(2722)

The type definition for `format` is:

https://github.com/panoply/prettify/blob/b48fb59f6aa2a06286a2ca55356244dd539423f2/index.d.ts#L46

I'm not a TypeScript expert, but doesn't that mean that the format property itself may be undefined? Should it be something like this instead?

```typescript
format: Format<Promise<string | undefined>>
```

As a workaround, this works but isn't ideal:

```typescript
if (prettify.format) {
  await prettify.format(sourceXml, { language: 'xml' });
}
```

Thanks!

**Comment by panoply** [comment]
Hey @bmaupin 

This project has moved to [Æsthetic](https://github.com/panoply/esthetic).
