### ISSUE TITLE
HTML: Attribute spanning new lines causes formatting to no longer be idempotent

### ISSUE THREAD

**Issue by washtubs** [panoply/prettify#3]
The following shows that if you prettify the code in a chain, it continually prefixes everything bellow the `attr=` line with spaces. Tested in `v0.4.4-beta1` and `v0.5.5-beta1`. Try removing a then block or two and see the difference.

    function prettifyCode(code) {
        return prettify.format(code, {
          language: 'html',
        });
    }
    
    function main() {

        let code=`
    <div attr="
    aaa
    bbb
    "></div>
    `

        prettifyCode(code).then((out) => {
            return prettifyCode(out);
        }).then((out) => {
            return prettifyCode(out);
        }).then((out) => {
            return prettifyCode(out);
        }).then((out) => {
            return prettifyCode(out);
        }).then((out) => {
            return prettifyCode(out);
        }).then((out) => {
            console.log(out)
        })
    }

    main();

**Comment by panoply** [comment]
Hey @washtubs 

This project has moved to [Æsthetic](https://github.com/panoply/esthetic). Promise resolution was experimental. Æsthetic executes synchronous.
